import {describe, expect, it} from 'vitest';
import {createDockDiagnostics} from './content-dock-diagnostics';
import {
  createDataSourceSettings,
  loadStoredBaseLayerId,
  loadStoredLayerSettings,
  loadStoredLifecycleSettings,
} from './content-storage-settings';

describe('createDockDiagnostics', () => {
  it('shapes diagnostics correctly with null plan', () => {
    const baseLayerId = loadStoredBaseLayerId();
    const dataSource = createDataSourceSettings('live');
    const lifecycleSettings = loadStoredLifecycleSettings();
    const layerSettings = loadStoredLayerSettings();

    const diagnostics = createDockDiagnostics({
      status: 'idle',
      intelUrl: 'https://intel.ingress.com',
      camera: {lat: 52.3, lng: 4.9, zoom: 15, bounds: null},
      plan: null,
      summaryMode: 'summary',
      requestBatches: [],
      entityFetch: {
        status: 'idle',
        entitySource: 'idle',
        authRequired: false,
        generation: 0,
        key: '',
        collision: false,
        portals: 0,
        realPortals: 0,
        placeholderPortals: 0,
        ornamentPortals: 0,
        drawnOrnamentMarkers: 0,
        hiddenOrnamentMarkers: 0,
        ornamentTypes: {},
        artifactPortals: 0,
        drawnArtifactMarkers: 0,
        artifactTypes: {},
        artifactFetchStatus: 'disabled',
        artifactFetchPortalCount: 0,
        artifactFetchTypes: [],
        artifactFetchElapsedMs: null,
        artifactFetchError: '',
        levelLabels: 0,
        damagedPortals: 0,
        links: 0,
        fields: 0,
        viewportPortals: 0,
        viewportRealPortals: 0,
        viewportPlaceholderPortals: 0,
        viewportLinks: 0,
        viewportFields: 0,
        viewportOrnamentPortals: 0,
        viewportOrnamentMarkers: 0,
        viewportArtifactPortals: 0,
        viewportArtifactMarkers: 0,
        requestedTiles: 0,
        returnedTiles: 0,
        nonEmptyTiles: 0,
        elapsedMs: null,
        firstRenderElapsedMs: null,
        retryRequests: 0,
        retriedTileKeys: [],
        recoveredTileKeys: [],
        emptyTileKeys: [],
        nonEmptyTileKeys: [],
        unaccountedTileKeys: [],
        serverRetryTileKeys: [],
        timeoutTileKeys: [],
        errorTileKeys: [],
        responseRetryTileKeys: [],
        queueDelayReasons: [],
        partialTileKeys: [],
        cacheFreshTileKeys: [],
        cacheStaleTileKeys: [],
        staleGenerationCacheWarmTileKeys: [],
        queue: null,
        renderQueue: null,
        renderMutation: null,
        timing: null,
        playerTracker: null,
        baseLayerId,
        dataSource,
        highlighterSettings: {active: 'none'},
        highlighterIds: ['none'],
        renderPolicy: {
          activeHighlighter: 'none',
          levelFill: false,
          healthFill: false,
          ornaments: true,
          artifacts: true,
          labels: true,
          optionalOverlayMinZoom: 15,
          detailedPortals: true,
        },
        selectedPortal: null,
        portalDetails: null,
        portalAnalysis: null,
      },
      baseLayerId,
      dataSource,
      requestDiagnostics: {
        activeRequests: 0,
        activeByEndpoint: {},
        active: [],
      },
      lifecycleSettings,
      layerSettings,
      activeSidePanel: null,
      agentState: {status: 'idle'},
      commState: {status: 'idle', tab: 'all', messages: 0},
      scoresState: {status: 'idle', requestState: 'idle', region: {status: 'idle'}},
      missionsState: {status: 'idle', requestState: 'idle', source: 'view', missions: []},
      passcodeState: {status: 'idle', requestState: 'idle'},
      inventoryState: {
        status: 'idle',
        requestState: 'idle',
        subscription: {status: 'unknown'},
        items: 0,
        keys: 0,
        portalsWithKeys: 0,
        capsules: 0,
        portalKeysForSelectedPortal: null,
      },
    });

    expect(diagnostics.app).toBe('IITC IRIS');
    expect(diagnostics.plan).toBeNull();
    expect((diagnostics.entities as Record<string, unknown>).complete).toBe(false);
  });
});
